### ISSUE TITLE
Broken after latest update

### ISSUE THREAD

**Issue by Cainemon** [Derro8/firefox-extensions#1]
First off, amazing job!
This is what crunchy misses the most and you did it by using local browser history! 
Thx for that!

But unfortunately since latest update the extension seens broken, whenever i try to check my history i got this error msg from crunchy
"An error has occurred. Please try again." and does not show any history of watched content.

**Comment by Derro8** [comment]
Thanks for the support,
Unfortunately, I have no idea why it does that, but if you were to refresh the page it should load.
I'll look into it further and hopefully come up with a fix.

**Comment by Cainemon** [comment]
> but if you were to refresh the page it should load properly.
well unfortunately that didn't work either.
i keep getting the same error  *Something went wrong. Please try again.*
and the watch history cames up as clean.
ive tested in another pc with firefox fresh install and got the same result. =/

**Comment by Derro8** [comment]
Sorry about that, try the newest update (0.0.16) it should fix this and if it doesn't let me know since I wasn't able to replicate it.

**Comment by Cainemon** [comment]
yes i did, i manually deleted the extension and download again 
Version 0.0.17

> And by chance is the account you're using's history empty?

no its not empty the shows watched on TV are there and i can check my history normally in the app or using google chrome.
It only shows empty when using the extensionm even if i watch a show using the extension the same wont display on history page.

**Comment by Cainemon** [comment]
> Nevermind seems to only work on firefox version 116 and not 115, I'll make sure to run tests in that version for now.

Ill try asap

**Comment by Derro8** [comment]
Alright I think I've figured out the issue, but I'll have to finish it up tomorrow since it's getting quite late for me.

Thanks for ironing out some stuff with me.

**Comment by Cainemon** [comment]
Nice!
No problem, and thank you.

**Comment by Derro8** [comment]
Alright, I'm pretty sure I've fixed it now.
Try it out and let me know if it works as well, so I can close this issue.

**Comment by Cainemon** [comment]
The error msg is gonne but the watched history still not showing

**Comment by Cainemon** [comment]
its working now!
the problem seens to be the profile
![image](https://github.com/Derro8/firefox-extensions/assets/34521717/9f5c21d7-d06f-41c5-809e-14715446084d)
it was displaying as profile 0 without profile pic only with crunchyroll icon, and i cant use the arrows to swap but after change profile name and refresh the extension work (still cant swap profiles trough arrows but i dont really need that anyway) 

ty so much!

**Comment by Derro8** [comment]
> (still cant swap profiles trough arrows but i dont really need that anyway)

Ah, sorry I didn't read this part.

Update 0.0.20 should fix this.

**Comment by Cainemon** [comment]
It's working! I even created a new profile just to check and it's working as intended I think, each with their own watch history.

**Comment by Derro8** [comment]
> How do i delete the extra profile? 

Unfortunately that isn't a feature I'll add it in the next update which should be tomorrow or today.
